alert("Registratsiya");
var fullName = prompt("1.ism");
console.log(fullName);
var yourSecondN = prompt("2.familya");
console.log(yourSecondN);
var yourOch = prompt("3.ochestvo");
console.log(yourOch);
var yourAge = prompt("4.yosh");
console.log(yourAge);
var yourGmail = prompt("5.Gmail akktz");
console.log(yourGmail);
var yourPhone = prompt("6.telefon nomeringiz");
console.log(yourPhone);
var yourStudy = prompt("7.oqshingiz");
console.log(yourStudy);
var yourCourse = prompt("8.nechinchi kursdasiz");
console.log(yourCourse);
var yourWork = prompt("9.ish joyiz");
console.log(yourWork);
var yourBrighday = prompt("10.tugulgan kuningiz");
console.log(yourBrighday);
